/**
 * List of maximum possible categories for expenses.
 */
export const categories = [
    { id: '1', name: 'Food' },
    { id: '2', name: 'Transport' },
    { id: '3', name: 'Entertainment' },
    { id: '4', name: 'Rent' },
    { id: '5', name: 'Utilities' },
    { id: '6', name: 'Shopping' },
    { id: '7', name: 'Healthcare' },
    { id: '8', name: 'Insurance' },
    { id: '9', name: 'Dining Out' },
    { id: '10', name: 'Education' },
    { id: '11', name: 'Groceries' },
    { id: '12', name: 'Savings' },
    { id: '13', name: 'Investments' },
    { id: '14', name: 'Pets' },
    { id: '15', name: 'Travel' },
    { id: '16', name: 'Fitness' },
    { id: '17', name: 'Subscriptions' },
    { id: '18', name: 'Debt Repayment' },
    { id: '19', name: 'Gifts' },
    { id: '20', name: 'Donations' },
];

// src/utils/config.ts
export const paymentMethods = [
    { id: '1', name: 'Cash' },
    { id: '2', name: 'Credit Card' },
    { id: '3', name: 'Debit Card' },
    { id: '4', name: 'Bank Transfer' },
    { id: '5', name: 'Mobile Payment' },
    { id: '6', name: 'Cryptocurrency' },
    { id: '7', name: 'PayPal' },
    { id: '8', name: 'Gift Card' },
    { id: '9', name: 'Check' },
    { id: '10', name: 'Prepaid Card' },
    { id: '11', name: 'Direct Debit' },
    { id: '12', name: 'Contactless Payment' },
    { id: '13', name: 'Apple Pay' },
    { id: '14', name: 'Google Pay' },
    { id: '15', name: 'Amazon Pay' },
    { id: '16', name: 'AliPay' },
    { id: '17', name: 'WeChat Pay' },
    { id: '18', name: 'Venmo' },
    { id: '19', name: 'Zelle' },
    { id: '20', name: 'Square Cash' },
    { id: '21', name: 'Stripe' },
    { id: '22', name: 'Western Union' },
    { id: '23', name: 'Money Order' },
    { id: '24', name: 'Boleto' },
    { id: '25', name: 'SEPA' },
    { id: '26', name: 'Klarna' },
    { id: '27', name: 'Afterpay' },
    { id: '28', name: 'Bitcoin' },  // Specific cryptocurrency examples
    { id: '29', name: 'Ethereum' },
    { id: '30', name: 'Litecoin' },
    { id: '31', name: 'USDC' },  // USD Coin (stablecoin)
];

// src/config/currencies.ts
export const currencies = [
    { code: 'USD', name: 'United States Dollar' },
    { code: 'EUR', name: 'Euro' },
    { code: 'INR', name: 'Indian Rupee' },
    { code: 'GBP', name: 'British Pound Sterling' },
    { code: 'JPY', name: 'Japanese Yen' },
    { code: 'AUD', name: 'Australian Dollar' },
    { code: 'CAD', name: 'Canadian Dollar' },
    { code: 'CHF', name: 'Swiss Franc' },
    { code: 'CNY', name: 'Chinese Yuan' },
    { code: 'HKD', name: 'Hong Kong Dollar' },
    { code: 'NZD', name: 'New Zealand Dollar' },
    { code: 'SEK', name: 'Swedish Krona' },
    { code: 'KRW', name: 'South Korean Won' },
    { code: 'SGD', name: 'Singapore Dollar' },
    { code: 'NOK', name: 'Norwegian Krone' },
    { code: 'MXN', name: 'Mexican Peso' },
    { code: 'BRL', name: 'Brazilian Real' },
    { code: 'RUB', name: 'Russian Ruble' },
    { code: 'ZAR', name: 'South African Rand' },
    { code: 'TRY', name: 'Turkish Lira' },
    { code: 'ILS', name: 'Israeli New Shekel' },
    { code: 'AED', name: 'United Arab Emirates Dirham' },
    { code: 'SAR', name: 'Saudi Riyal' },
    { code: 'THB', name: 'Thai Baht' },
    { code: 'MYR', name: 'Malaysian Ringgit' },
    { code: 'PHP', name: 'Philippine Peso' },
    { code: 'IDR', name: 'Indonesian Rupiah' },
    { code: 'PKR', name: 'Pakistani Rupee' },
    { code: 'VND', name: 'Vietnamese Dong' },
    { code: 'EGP', name: 'Egyptian Pound' },
    { code: 'ARS', name: 'Argentine Peso' },
    { code: 'COP', name: 'Colombian Peso' },
    { code: 'PLN', name: 'Polish Zloty' },
    { code: 'CZK', name: 'Czech Koruna' },
    { code: 'HUF', name: 'Hungarian Forint' },
    { code: 'DKK', name: 'Danish Krone' },
    { code: 'BGN', name: 'Bulgarian Lev' },
    { code: 'RON', name: 'Romanian Leu' },
    { code: 'HRK', name: 'Croatian Kuna' },
    { code: 'BHD', name: 'Bahraini Dinar' },
    { code: 'KWD', name: 'Kuwaiti Dinar' },
    { code: 'QAR', name: 'Qatari Riyal' },
    { code: 'JOD', name: 'Jordanian Dinar' },
    { code: 'OMR', name: 'Omani Rial' },
    { code: 'TWD', name: 'Taiwan Dollar' },
    { code: 'CLP', name: 'Chilean Peso' },
    { code: 'NGN', name: 'Nigerian Naira' },
    { code: 'GHS', name: 'Ghanaian Cedi' },
    { code: 'KES', name: 'Kenyan Shilling' },
    { code: 'TZS', name: 'Tanzanian Shilling' },
    { code: 'UGX', name: 'Ugandan Shilling' },
    { code: 'MAD', name: 'Moroccan Dirham' },
    { code: 'DZD', name: 'Algerian Dinar' },
    { code: 'TND', name: 'Tunisian Dinar' },
    { code: 'LBP', name: 'Lebanese Pound' },
    { code: 'SYP', name: 'Syrian Pound' },
    { code: 'IQD', name: 'Iraqi Dinar' },
    { code: 'LYD', name: 'Libyan Dinar' },
    { code: 'AFN', name: 'Afghan Afghani' },
    { code: 'BDT', name: 'Bangladeshi Taka' },
    { code: 'KHR', name: 'Cambodian Riel' },
    { code: 'LAK', name: 'Laotian Kip' },
    { code: 'MMK', name: 'Burmese Kyat' },
    { code: 'LKR', name: 'Sri Lankan Rupee' },
    { code: 'MVR', name: 'Maldivian Rufiyaa' },
    { code: 'NPR', name: 'Nepalese Rupee' },
    { code: 'BND', name: 'Brunei Dollar' },
    { code: 'FJD', name: 'Fijian Dollar' },
    { code: 'XPF', name: 'CFP Franc' },
    { code: 'XOF', name: 'West African CFA Franc' },
    { code: 'XAF', name: 'Central African CFA Franc' },
    { code: 'MUR', name: 'Mauritian Rupee' },
    { code: 'SCR', name: 'Seychellois Rupee' },
    { code: 'ZMW', name: 'Zambian Kwacha' },
    { code: 'MWK', name: 'Malawian Kwacha' },
    { code: 'BWP', name: 'Botswana Pula' },
    { code: 'NAD', name: 'Namibian Dollar' },
    { code: 'SZL', name: 'Swazi Lilangeni' },
    { code: 'ETB', name: 'Ethiopian Birr' },
    { code: 'SDG', name: 'Sudanese Pound' },
    { code: 'BIF', name: 'Burundian Franc' },
    { code: 'CDF', name: 'Congolese Franc' },
    { code: 'MGA', name: 'Malagasy Ariary' },
    { code: 'GNF', name: 'Guinean Franc' },
    { code: 'XCD', name: 'East Caribbean Dollar' },
    { code: 'JMD', name: 'Jamaican Dollar' },
    { code: 'TTD', name: 'Trinidad and Tobago Dollar' },
    { code: 'BSD', name: 'Bahamian Dollar' },
    { code: 'BBD', name: 'Barbadian Dollar' },
    { code: 'HTG', name: 'Haitian Gourde' },
    { code: 'GYD', name: 'Guyanese Dollar' },
    { code: 'SRD', name: 'Surinamese Dollar' },
    { code: 'PYG', name: 'Paraguayan Guarani' },
    { code: 'UYU', name: 'Uruguayan Peso' },
    { code: 'BZD', name: 'Belize Dollar' },
    { code: 'HNL', name: 'Honduran Lempira' },
    { code: 'GTQ', name: 'Guatemalan Quetzal' },
    { code: 'NIO', name: 'Nicaraguan Córdoba' },
    { code: 'PAB', name: 'Panamanian Balboa' },
    { code: 'DOP', name: 'Dominican Peso' },
];